server:
  port: 8089
  shutdown: graceful
  undertow:
    threads:
      io: 100
      worker: 1000

customer-service:
  url: http://localhost:8082

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: Hieu2004@
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariCP

jwt:
  duration: 900 # 15 minutes
  secret: 4An32HWrMUxVr0TH6ZrV6p+g/cT8KCwz34w7h7FdTc6h8mbIvAygs5DcfeiDtqFKm84/t4OeifghoVCBuymmtQ==
  refresh-duration: 604800 # 7 days