CREATE TABLE PRIVILEGE
(
    ID   SERIAL,
    NAME TEXT,
    CONSTRAINT PRIVILEGE_PK PRIMARY KEY (ID)
);

CREATE TABLE PROFILE
(
    ID   SERIAL,
    NAME TEXT,
    CONSTRAINT PROFILE_PK PRIMARY KEY (ID)
);

CREATE TABLE PROFILE_PRIVILEGE
(
    PROFILE_ID   INTEGER,
    PRIVILEGE_ID INTEGER,
    CONSTRAINT PROFILE_ID_FK FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE (ID),
    CONSTRAINT PRIVILEGE_ID_FK FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGE (ID)
);

CREATE TABLE USER_ACCOUNT
(
    ID         SERIAL,
    NAME       TEXT,
    USERNAME   TEXT,
    PASSWORD   TEXT,
    ACTIVE     BOOLEAN,
    PROFILE_ID INTEGER,
    CONSTRAINT USER_ACCOUNT_PK PRIMARY KEY (ID),
    CONSTRAINT PROFILE_ID_FK FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE (ID)
);

CREATE TABLE CLIENT_DETAILS
(
    ID                     SERIAL,
    CLIENT_ID              TEXT,
    CLIENT_SECRET          TEXT,
    GRANT_TYPES            TEXT,
    SCOPES                 TEXT,
    RESOURCES              TEXT,
    REDIRECT_URIS          TEXT,
    ACCESS_TOKEN_VALIDITY  INTEGER,
    REFRESH_TOKEN_VALIDITY INTEGER,
    SECRET_REQUIRED        BOOLEAN,
    CONSTRAINT CLIENT_DETAILS_PK PRIMARY KEY (ID)
);