CREATE TABLE IF NOT EXISTS PRIVILEGE
(
    ID   SERIAL,
    NAME TEXT,
    CONSTRAINT PRIVILEGE_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PROFILE
(
    ID   SERIAL,
    NAME TEXT,
    CONSTRAINT PROFILE_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PROFILE_PRIVILEGE
(
    PROFILE_ID   INTEGER,
    PRIVILEGE_ID INTEGER,
    CONSTRAINT PROFILE_ID_FK FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE (ID),
    CONSTRAINT PRIVILEGE_ID_FK FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGE (ID)
);

CREATE TABLE IF NOT EXISTS USER_ACCOUNT
(
    ID         SERIAL,
    NAME       TEXT NOT NULL ,
    USERNAME   TEXT NOT NULL UNIQUE ,
    PASSWORD   TEXT NOT NULL,
    ACTIVE     BOOLEAN NOT NULL,
    PROFILE_ID INTEGER,
    CONSTRAINT USER_ACCOUNT_PK PRIMARY KEY (ID),
    CONSTRAINT PROFILE_ID_FK FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE (ID)
);

CREATE TABLE IF NOT EXISTS CLIENT_DETAILS
(
    ID                     SERIAL,
    CLIENT_ID              TEXT,
    CLIENT_SECRET          TEXT,
    GRANT_TYPES            TEXT,
    SCOPES                 TEXT,
    RESOURCES              TEXT,
    REDIRECT_URIS          TEXT,
    ACCESS_TOKEN_VALIDITY  INTEGER,
    REFRESH_TOKEN_VALIDITY INTEGER,
    SECRET_REQUIRED        BOOLEAN,
    CONSTRAINT CLIENT_DETAILS_PK PRIMARY KEY (ID)
);